# Generated by Django 2.0.10 on 2019-03-23 23:46

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=100)),
                ('calendar_id', models.CharField(max_length=100)),
                ('iso_date_time', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='The Frequently Asked Question', max_length=200)),
                ('answer', models.TextField(help_text='Answer to the question')),
            ],
        ),
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=13)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sccalendar.Event')),
            ],
        ),
        migrations.CreateModel(
            name='StaticEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(help_text='Enter event name', max_length=100)),
                ('event_details', models.CharField(blank=True, help_text='Enter event details (times ect.)', max_length=200, null=True)),
                ('event_address', models.CharField(blank=True, help_text='Enter event address', max_length=200, null=True)),
                ('event_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True)),
                ('event_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('event_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
