# Generated by Django 2.0.10 on 2019-03-23 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sccalendar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(help_text='The Frequently Asked Question', max_length=200)),
                ('answer', models.TextField(help_text='Answer to the question')),
            ],
        ),
    ]
