# Generated by Django 2.0.2 on 2019-02-09 02:01

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('sccalendar', '0002_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(help_text='Enter event name', max_length=100)),
                ('event_details', models.CharField(blank=True, help_text='Enter event details (times ect.)', max_length=200, null=True)),
                ('event_address', models.CharField(blank=True, help_text='Enter event address', max_length=200, null=True)),
                ('event_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True)),
                ('event_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('event_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
